const repositories = [
  {
    id: 1,
    repo: 'Repo 1',
    time: '2 hours ago',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'Medium',
  },
  {
    id: 2,
    repo: 'Repo 2',
    time: '1 day ago',
    IssueCount: '5',
    openIssue: '1 open',
    errorStatus: 'High',
  },
  {
    id: 3,
    repo: 'Repo 3',
    time: '1 day ago',
    IssueCount: '5',
    openIssue: '1 open',
    errorStatus: 'Low',
  },
  {
    id: 4,
    repo: 'Repo 4',
    time: 'Jul 30, 2024 9:05 am',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'Low',
  },
  {
    id: 5,
    repo: 'Repo 5',
    time: 'JJul 18, 2024 7:45 am',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'High',
  },
  {
    id: 6,
    repo: 'Repo 6',
    time: 'Aug 3, 2024 1:52 am',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'High',
  },
  {
    id: 7,
    repo: 'Repo 7',
    time: 'Jul 22, 2024 9:55 pm',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'Low',
  },
  {
    id: 8,
    repo: 'Repo 8',
    time: 'Jul 8, 2024 12:00 pm',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'Low',
  },
  {
    id: 9,
    repo: 'Repo 9',
    time: 'Jul 21, 2024 3:59 pm',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'Medium',
  },
  {
    id: 10,
    repo: 'Repo 10',
    time: 'Jul 12, 2024 3:04 am',
    IssueCount: '10',
    openIssue: '3 open',
    errorStatus: 'Medium',
  },
];

export default repositories;
